on:
  workflow_dispatch:

jobs:
  sync-milestones:
    runs-on: ubuntu-latest
    name: Sync Milestones 
    steps:
      - name: Sync Milestones 
        id: sync-milestones
        uses: deanhigh/sample-action@v0.0.2
        with:
          repositories: 'testrepo'
          token: ${{ secrets.GITHUB_TOKEN }}