on:
  workflow_dispatch:

jobs:
  push-project-artifacts:
    runs-on: ubuntu-latest
    name: Push Project Artifacts 
    steps:
      - name: Push Milestones 
        id: push-milestones
        uses: deanhigh/multirepo-project-actions@main
        with:
          repositories: 'deanhigh/test-multirepo-project-actions-sink-a/milestone-push'
          token: ${{ secrets.CROSS_REPO_PAT }}
