on:
  workflow_dispatch:

jobs:
  sync-milestones:
    runs-on: ubuntu-latest
    name: Sync Milestones 
    steps:
      - name: Copy Milestones 
        id: copy-milestones
        uses: deanhigh/milestone-sync-action@main
        with:
          repositories: 'deanhigh/milestone-sync-action,deanhigh/sample-action'
          token: ${{ secrets.CROSS_REPO_PAT }}
